name: flutter_bloc_template
description: A new Flutter project.  # Description of your Flutter project
publish_to: 'none'  # Publishing destination (e.g., 'none' means not publishing to any package repository)
version: 0.1.0  # Version number of your project

environment:
  sdk: '>=3.0.6 <4.0.0'  # Required Flutter SDK version range for compatibility

dependencies:
  flutter:
    sdk: flutter  # Flutter SDK dependency
  retrofit: ^4.0.1  # Retrofit HTTP client library
  json_annotation: ^4.8.1  # JSON serialization/deserialization library
  dio: ^5.3.2  # Dio HTTP client library
  equatable: ^2.0.5  # Library for equality comparisons
  flutter_bloc: ^8.1.3  # BLoC state management library for Flutter
  get_it: ^7.6.0  # Dependency injection library

dev_dependencies:
  flutter_test:
    sdk: flutter  # Flutter test dependency
  flutter_lints: ^2.0.0  # Linting rules for Flutter projects
  json_serializable: ^6.7.1  # Code generation for JSON serialization
  build_runner: ^2.4.6  # Code generation tasks runner
  retrofit_generator: ^7.0.8  # Code generation for Retrofit

flutter:
  uses-material-design: true  # Indicates that the app follows Material Design guidelines
